### PR TITLE
Add function for checking many invariants about data structures

### PR DESCRIPTION
**Pull request by jafingerhut**
This is a bit raw right now, perhaps, but I wanted to throw it over to you to see if you thought it would be of any interest.  It is a new namespace with a few functions that can check the ubergraph internal data structures to see whether they satisfy various conditions, that I think are intended to be always true, i.e. invariants.  It returns any violations it finds.

In this PR, the new code is not used at all in any "production path" code.  I did add a bunch of calls to the invariant checker in the tests, and they all still pass.

### CODE REVIEW

**Comment by Engelberg** [comment]
So what is the main objective here? To support richer tests? I'm all for that.

**Comment by jafingerhut** [comment]
These are certainly the kinds of checks that can be added to pretty much any tests, and could help in finding violations of the checks.  One of the checks was motivated by a violation of it that I found while examining how add-attr works.

**Comment by Engelberg** [comment]
OK. Well, since you said it is "raw" right now, just let me know when you have this in a state where you'd like me to merge it.

Are you saying there is currently a bug in add-attr?

**Comment by jafingerhut** [comment]
Created issue https://github.com/Engelberg/ubergraph/issues/48 for maybe-bug in add-attr

**Comment by jafingerhut** [comment]
I've cleaned up some of the comments and shortened some way too long function names.  I think it should be ready to merge, but please do look it over if you get a chance, and let me know if you have any suggestions for improvements.

**Pull request merged**
